services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    command: uvicorn app.app:app --host 0.0.0.0 --port $PORT
    ports:
      - 8888:8888
