services:
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
    command: uvicorn app.api.app:app --reload --workers 1 --host 0.0.0.0 --port 8888
    ports:
      - 8888:8888
