services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    command: uvicorn app.app:app --reload --host 0.0.0.0 --port 8888
    ports:
      - 8888:8888
