# version: "3.7"

# services:
#   api:
#     build: .
#     container_name: "api"
#     # volumes:
#     #   - ./app:/app
#     volumes:
#       - ./app:/
#     ports:
#       - 3000:3000

version: "3.7"
services:
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
    command: uvicorn app.api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
